// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: bidirectional.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidirectional_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_bidirectional_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_bidirectional_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bidirectional_proto protoreflect.FileDescriptor

var file_bidirectional_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x49, 0x0a, 0x0c, 0x42, 0x69, 0x64, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x12, 0x39, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bidirectional_proto_rawDescOnce sync.Once
	file_bidirectional_proto_rawDescData = file_bidirectional_proto_rawDesc
)

func file_bidirectional_proto_rawDescGZIP() []byte {
	file_bidirectional_proto_rawDescOnce.Do(func() {
		file_bidirectional_proto_rawDescData = protoimpl.X.CompressGZIP(file_bidirectional_proto_rawDescData)
	})
	return file_bidirectional_proto_rawDescData
}

var file_bidirectional_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bidirectional_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: proto.Message
}
var file_bidirectional_proto_depIdxs = []int32{
	0, // 0: proto.Bidrectional.GetServerResponse:input_type -> proto.Message
	0, // 1: proto.Bidrectional.GetServerResponse:output_type -> proto.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bidirectional_proto_init() }
func file_bidirectional_proto_init() {
	if File_bidirectional_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bidirectional_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bidirectional_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidirectional_proto_goTypes,
		DependencyIndexes: file_bidirectional_proto_depIdxs,
		MessageInfos:      file_bidirectional_proto_msgTypes,
	}.Build()
	File_bidirectional_proto = out.File
	file_bidirectional_proto_rawDesc = nil
	file_bidirectional_proto_goTypes = nil
	file_bidirectional_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BidrectionalClient is the client API for Bidrectional service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BidrectionalClient interface {
	GetServerResponse(ctx context.Context, opts ...grpc.CallOption) (Bidrectional_GetServerResponseClient, error)
}

type bidrectionalClient struct {
	cc grpc.ClientConnInterface
}

func NewBidrectionalClient(cc grpc.ClientConnInterface) BidrectionalClient {
	return &bidrectionalClient{cc}
}

func (c *bidrectionalClient) GetServerResponse(ctx context.Context, opts ...grpc.CallOption) (Bidrectional_GetServerResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Bidrectional_serviceDesc.Streams[0], "/proto.Bidrectional/GetServerResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &bidrectionalGetServerResponseClient{stream}
	return x, nil
}

type Bidrectional_GetServerResponseClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type bidrectionalGetServerResponseClient struct {
	grpc.ClientStream
}

func (x *bidrectionalGetServerResponseClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bidrectionalGetServerResponseClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BidrectionalServer is the server API for Bidrectional service.
type BidrectionalServer interface {
	GetServerResponse(Bidrectional_GetServerResponseServer) error
}

// UnimplementedBidrectionalServer can be embedded to have forward compatible implementations.
type UnimplementedBidrectionalServer struct {
}

func (*UnimplementedBidrectionalServer) GetServerResponse(Bidrectional_GetServerResponseServer) error {
	return status.Errorf(codes.Unimplemented, "method GetServerResponse not implemented")
}

func RegisterBidrectionalServer(s *grpc.Server, srv BidrectionalServer) {
	s.RegisterService(&_Bidrectional_serviceDesc, srv)
}

func _Bidrectional_GetServerResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BidrectionalServer).GetServerResponse(&bidrectionalGetServerResponseServer{stream})
}

type Bidrectional_GetServerResponseServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type bidrectionalGetServerResponseServer struct {
	grpc.ServerStream
}

func (x *bidrectionalGetServerResponseServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bidrectionalGetServerResponseServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Bidrectional_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Bidrectional",
	HandlerType: (*BidrectionalServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetServerResponse",
			Handler:       _Bidrectional_GetServerResponse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bidirectional.proto",
}
